//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Molecular Weight Calculator.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDD_MwtABOUTBOX                 101
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     129
#define ID_FORMULA_LISTMASSES           133
#define ID_FORMULA_LISTGROUPS           134
#define IDB_UP                          135
#define IDB_DOWN                        136
#define ID_GROUP_LIST                   138
#define ID_PERIODIC_PERIODICTABLE       139
#define IDD_PERIODICTABLE               140
#define IDD_ELEMENT_DLG                 141
#define IDD_ELECTROSPRAY                142
#define ID_ISOTOPEMODELER_ELECTROSPRAYMODELER 143
#define IDD_PRINT_LISTCTRL              176
#define IDD_MOLECULARWEIGHTCALCULATOR_DIALOG 198
#define IDD_GEN_DLG                     200
#define IDS_ABOUTBOXELEMENT             305
#define IDS_ABOUTBOX                    306
#define IDC_EDITFORMULA                 1000
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_COPY_BUTTON                 1002
#define IDC_EDIT_INTENSITY_LIMIT        1003
#define IDC_STATIC_FORMULA              1004
#define IDC_CHECKHplus                  1005
#define IDC_CHECKNaplus                 1006
#define IDC_CHECKKplus                  1007
#define IDC_CHECKNH4plus                1008
#define IDC_CHECKHminus                 1009
#define IDC_CHECKClminus                1010
#define IDC_RADIOpos                    1011
#define IDC_BUTTONCalculate             1013
#define IDC_RADIOneg                    1014
#define IDC_BUTTONPrint                 1032
#define IDC_BUTTONSaveAs                1033
#define IDC_EDIT3                       1034
#define IDC_BUTTONPrint2                1034
#define IDC_COPY_BUTTON2                1036
#define IDC_BUTTON2                     1038
#define IDC_BUTTON3                     1039
#define IDC_BUTTON4                     1040
#define IDC_BUTTON5                     1041
#define IDC_BUTTON6                     1043
#define IDC_BUTTON7                     1044
#define IDC_BUTTON8                     1045
#define IDC_STATIC_Searched             1046
#define IDC_BUTTON9                     1048
#define IDC_BUTTON10                    1049
#define IDC_HELPBUTTON                  1049
#define IDC_BUTTON11                    1050
#define IDC_BUTTONPRINTTABLE            1050
#define IDC_BUTTON12                    1051
#define IDC_STATICMolecularWeight       1051
#define IDC_BUTTON13                    1052
#define IDC_STATICAverageMwt            1052
#define IDC_BUTTON14                    1053
#define IDC_STATICMassPercent           1053
#define IDC_BUTTON15                    1054
#define IDC_BUTTON1                     1054
#define IDC_RADIO1NEUTRAL               1055
#define IDC_RADIO2POSITIVE              1056
#define IDC_RADIO3                      1057
#define IDC_RADIO3NEGATIVE              1057
#define IDC_SAVE_AS_BUTTON              1062
#define IDC_PRINT_BUTTON                1063
#define IDC_LIST2                       1067
#define IDC_COPY_SPECTRUM               1068
#define IDC_SAMPLE                      1074
#define IDC_CHECKTC                     1087
#define IDC_CHECKPH                     1088
#define IDC_CHECKRC                     1089
#define IDC_CHECKLS                     1090
#define IDC_HYDROGEN                    1090
#define IDC_CHECKCS                     1091
#define IDC_EXACTMASS                   1091
#define IDC_CHECKPL                     1092
#define IDC_LITHIUM                     1092
#define IDC_BUTTONFOOTER                1093
#define IDC_BERYLIUM                    1093
#define IDC_BUTTONHEADER                1094
#define IDC_SODIUM                      1094
#define IDC_CHECKPF                     1095
#define IDC_MAGNESIUM                   1095
#define IDC_CHECKPHR                    1096
#define IDC_POTASSIUM                   1096
#define IDC_CHECKPFR                    1097
#define IDC_CALCIUM                     1097
#define IDC_BUTTONLISTF                 1098
#define IDC_SCANDIUM                    1098
#define IDC_TITANIUM                    1099
#define IDC_VANADIUM                    1100
#define IDC_CHROMIUM                    1101
#define IDC_MANGANESE                   1102
#define IDC_IRON                        1103
#define IDC_COBALT                      1104
#define IDC_NICKEL                      1105
#define IDC_COPPER                      1106
#define IDC_ZINC                        1107
#define IDC_BORON                       1108
#define IDC_CARBON                      1109
#define IDC_ALUMINUM                    1110
#define IDC_SILICON                     1111
#define IDC_GALLIUM                     1112
#define IDC_GERMANIUM                   1113
#define IDC_NITROGEN                    1114
#define IDC_OXYGEN                      1115
#define IDC_PHOSPHORUS                  1116
#define IDC_SULFUR                      1117
#define IDC_ARSENIC                     1118
#define IDC_SELENIUM                    1119
#define IDC_FLOURINE                    1120
#define IDC_NEON                        1121
#define IDC_CHLORINE                    1122
#define IDC_ARGON                       1123
#define IDC_BROMINE                     1124
#define IDC_KRYPTON                     1125
#define IDC_HELIUM                      1126
#define IDC_RUBIDIUM                    1127
#define IDC_PRINT_SETUP                 1128
#define IDC_STRONTIUM                   1128
#define IDC_YTTRIUM                     1129
#define IDC_ZIRCONIUM                   1130
#define IDC_NIOBIUM                     1131
#define IDC_MOLYBDENUM                  1132
#define IDC_TECHNETIUM                  1133
#define IDC_RUTHENIUM                   1134
#define IDC_RHODIUM                     1135
#define IDC_PALLADIUM                   1136
#define IDC_SILVER                      1137
#define IDC_CADMIUM                     1138
#define IDC_INDIUM                      1139
#define IDC_TIN                         1140
#define IDC_ANTIMONY                    1141
#define IDC_TELLURIUM                   1142
#define IDC_IODINE                      1143
#define IDC_XENON                       1144
#define IDC_CESIUM                      1145
#define IDC_BARIUM                      1146
#define IDC_LUTETIUM                    1147
#define IDC_HAFNIUM                     1148
#define IDC_TANTALUM                    1149
#define IDC_TUNGSTEN                    1150
#define IDC_RHENIUM                     1151
#define IDC_STATIC_HITS                 1152
#define IDC_OSMIUM                      1152
#define IDC_IRIDIUM                     1153
#define IDC_PLATINUM                    1154
#define IDC_GOLD                        1155
#define IDC_MERCURY                     1156
#define IDC_THALLIUM                    1157
#define IDC_LEAD                        1158
#define IDC_BISMUTH                     1159
#define IDC_POLONIUM                    1160
#define IDC_ASTATINE                    1161
#define IDC_RADON                       1162
#define IDC_FRANCIUM                    1163
#define IDC_RADIUM                      1164
#define IDC_LAWRENCIUM                  1165
#define IDC_LANTHANUM                   1166
#define IDC_CERIUM                      1167
#define IDC_PRASEODYMIUM                1168
#define IDC_NEODYMIUM                   1169
#define IDC_PROMETHIUM                  1170
#define IDC_SAMARIUM                    1171
#define IDC_EUROPIUM                    1172
#define IDC_GADOLINIUM                  1173
#define IDC_TERBIUM                     1174
#define IDC_DYSPROSIUM                  1175
#define IDC_HOLMIUM                     1176
#define IDC_ERBIUM                      1177
#define IDC_THULIUM                     1178
#define IDC_YTTERBIUM                   1179
#define IDC_ACTINIUM                    1180
#define IDC_THORIUM                     1181
#define IDC_PROTACTINIUM                1182
#define IDC_URANIUM                     1183
#define IDC_NEPTUNIUM                   1184
#define IDC_PLUTONIUM                   1185
#define IDC_AMERICIUM                   1186
#define IDC_CURIUM                      1187
#define IDC_BERKELIUM                   1188
#define IDC_CALIFORNIUM                 1189
#define IDC_EINSTEINIUM                 1190
#define IDC_FERMIUM                     1191
#define IDC_MENDELEVIUM                 1192
#define IDC_NOBELIUM                    1193
#define IDC_EDITC_min                   1302
#define IDC_EDITC_max                   1303
#define IDC_EDITC13_min                 1304
#define IDC_EDITC13_max                 1305
#define IDC_EDITH_min                   1306
#define IDC_EDITH_max                   1307
#define IDC_EDITD_min                   1308
#define IDC_EDITD_max                   1309
#define IDC_EDITN_min                   1310
#define IDC_EDITN_max                   1311
#define IDC_EDITN15_min                 1314
#define IDC_EDITN15_max                 1315
#define IDC_EDITO_min                   1316
#define IDC_EDITO_max                   1317
#define IDC_EDITF_min                   1318
#define IDC_EDITF_max                   1319
#define IDC_EDITNa_min                  1320
#define IDC_EDITNa_max                  1321
#define IDC_EDITSi_min                  1322
#define IDC_EDITSi_max                  1323
#define IDC_EDITP_min                   1324
#define IDC_EDITP_max                   1325
#define IDC_EDITS_min                   1326
#define IDC_EDITS_max                   1327
#define IDC_EDITCl_min                  1328
#define IDC_EDITCl_max                  1329
#define IDC_EDITBr_min                  1330
#define IDC_EDITBr_max                  1331
#define IDC_LIST1                       2029
#define ID_FORMULA_DLG                  32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
